In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# URL situs web yang akan di-scrape
url = 'https://id.wikipedia.org/wiki/Daftar_musik_Indonesia_terpopuler_di_Spotify'

respon = requests.get(url)

In [3]:
# cek kalau respons berhasil diunduh
if respon.status_code == 200:
    
    # Membuat objek Beautiful Soup untuk mengurai HTML
    soup = BeautifulSoup(respon.text, 'html.parser')

    # Mencari tabel dengan class 'wikitable'
    tabel = soup.find('table', {'class': 'wikitable'})

    # Membaca tabel dan mengonversinya ke dalam DataFrame pandas
    df = pd.read_html(str(tabel))[0]  
    
    # Menampilkan DataFrame
    display(df)

else:
    print('Gagal mengunduh halaman web. Kode status:', response.status_code)

,No. urut,Artis,Total pemutaran,Basis karier,Tahun debut rekaman,Ref.
0,1,Rich Brian,"2,69 miliar",Amerika Serikat,2016,[5]
1,2,Niki,"2,47 miliar",Amerika Serikat,2014,[6]
2,3,Tulus,"2,12 miliar",Indonesia,2011,[7]
3,4,Pamungkas,"1,31 miliar",Indonesia,2018,[8]
4,5,Noah,"1,16 miliar[a]",Indonesia,2002,[9][10]
5,6,Sheila on 7,"1,08 miliar",Indonesia,1999,[11]
6,7,Fiersa Besari,"1,07 miliar",Indonesia,2012,[12]
7,8,Mahalini,"1,06 miliar",Indonesia,2015,[13]
8,9,Dewa 19,"1,05 miliar[b]",Indonesia,1992,[14][15]
9,10,Rizky Febian,"0,93 miliar",Indonesia,2012,[16]
10,Data per 30 September 2023,Data per 30 September 2023,Data per 30 September 2023,Data per 30 September 2023,Data per 30 September 2023,Data per 30 September 2023